-- ms/init.lua
local path = minetest.get_modpath("ms")

dofile(path .. "/api.lua")
dofile(path .. "/carpets.lua")
dofile(path .. "/cobweb.lua")
dofile(path .. "/concrete.lua")
dofile(path .. "/fireworks.lua")
dofile(path .. "/flowers.lua")
dofile(path .. "/glass.lua")
dofile(path .. "/lightblue.lua")
dofile(path .. "/shears.lua")
dofile(path .. "/tiles.lua")
dofile(path .. "/walls.lua")
dofile(path .. "/wire.lua")
